USERNAMES = ['jimcramer'] # 'LizAnnSonders', 'morganhousel', 'charliebilello'
DIRECTORIES = ['historical', 'mentions', 'tweets', 'users']
COMPANIES = {
    "3M":"MMM",
    "A. O. Smith":"AOS",
    "Abbott":"ABT",
    "AbbVie":"ABBV",
    "Abiomed":"ABMD",
    "Accenture":"ACN",
    "Activision Blizzard":"ATVI",
    "ADM":"ADM",
    "Adobe Inc.":"ADBE",
    "ADP":"ADP",
    "Advance Auto Parts":"AAP",
    "AES Corporation":"AES",
    "Aflac":"AFL",
    "Agilent Technologies":"A",
    "Air Products and Chemicals":"APD",
    "Akamai":"AKAM",
    "Alaska Air Group":"ALK",
    "Albemarle Corporation":"ALB",
    "Alexandria Real Estate Equities":"ARE",
    "Align Technology":"ALGN",
    "Allegion":"ALLE",
    "Alliant Energy":"LNT",
    "Allstate":"ALL",
    "Alphabet Inc. (Class A)":"GOOGL",
    "Alphabet Inc. (Class C)":"GOOG",
    "Altria":"MO",
    "Amazon":"AMZN",
    "Amcor":"AMCR",
    "AMD":"AMD",
    "Ameren":"AEE",
    "American Airlines Group":"AAL",
    "American Electric Power":"AEP",
    "American Express":"AXP",
    "American International Group":"AIG",
    "American Tower":"AMT",
    "American Water Works":"AWK",
    "Ameriprise Financial":"AMP",
    "AmerisourceBergen":"ABC",
    "Ametek":"AME",
    "Amgen":"AMGN",
    "Amphenol":"APH",
    "Analog Devices":"ADI",
    "Ansys":"ANSS",
    "Anthem":"ANTM",
    "Aon":"AON",
    "APA Corporation":"APA",
    "Apple Inc.":"AAPL",
    "Applied Materials":"AMAT",
    "Aptiv":"APTV",
    "Arista Networks":"ANET",
    "Arthur J. Gallagher & Co.":"AJG",
    "Assurant":"AIZ",
    "AT&T":"T",
    "Atmos Energy":"ATO",
    "Autodesk":"ADSK",
    "AutoZone":"AZO",
    "AvalonBay Communities":"AVB",
    "Avery Dennison":"AVY",
    "Baker Hughes":"BKR",
    "Ball Corporation":"BALL",
    "Bank of America":"BAC",
    "Bath & Body Works":"BBWI",
    "Baxter International":"BAX",
    "Becton Dickinson":"BDX",
    "Berkley":"WRB",
    "Berkshire Hathaway":"BRK.B",
    "Best Buy":"BBY",
    "Bio-Rad":"BIO",
    "Bio-Techne":"TECH",
    "Biogen":"BIIB",
    "BlackRock":"BLK",
    "BNY Mellon":"BK",
    "Boeing":"BA",
    "Booking Holdings":"BKNG",
    "BorgWarner":"BWA",
    "Boston Properties":"BXP",
    "Boston Scientific":"BSX",
    "Bristol Myers Squibb":"BMY",
    "Broadcom Inc.":"AVGO",
    "Broadridge Financial Solutions":"BR",
    "Brown & Brown":"BRO",
    "Brown–Forman":"BF.B",
    "C.H. Robinson":"CHRW",
    "Cadence Design Systems":"CDNS",
    "Caesars Entertainment":"CZR",
    "Camden Property Trust":"CPT",
    "Campbell Soup Company":"CPB",
    "Capital One":"COF",
    "Cardinal Health":"CAH",
    "CarMax":"KMX",
    "Carnival":"CCL",
    "Carrier Global":"CARR",
    "Catalent":"CTLT",
    "Caterpillar Inc.":"CAT",
    "Cboe Global Markets":"CBOE",
    "CBRE Group":"CBRE",
    "CDW":"CDW",
    "Celanese":"CE",
    "Centene Corporation":"CNC",
    "CenterPoint Energy":"CNP",
    "Ceridian":"CDAY",
    "CF Industries":"CF",
    "Charles River Laboratories":"CRL",
    "Charles Schwab Corporation":"SCHW",
    "Charter Communications":"CHTR",
    "Chevron Corporation":"CVX",
    "Chipotle Mexican Grill":"CMG",
    "Chubb Limited":"CB",
    "Church & Dwight":"CHD",
    "Cigna":"CI",
    "Cincinnati Financial":"CINF",
    "Cintas":"CTAS",
    "Cisco":"CSCO",
    "Citigroup":"C",
    "Citizens Financial Group":"CFG",
    "Citrix":"CTXS",
    "Clorox":"CLX",
    "CME Group":"CME",
    "CMS Energy":"CMS",
    "The Coca-Cola Company":"KO",
    "Cognizant":"CTSH",
    "Colgate-Palmolive":"CL",
    "Comcast":"CMCSA",
    "Comerica":"CMA",
    "Conagra Brands":"CAG",
    "ConocoPhillips":"COP",
    "Consolidated Edison":"ED",
    "Constellation Brands":"STZ",
    "Constellation Energy":"CEG",
    "CooperCompanies":"COO",
    "Copart":"CPRT",
    "Corning Inc.":"GLW",
    "Corteva":"CTVA",
    "Costco":"COST",
    "Coterra":"CTRA",
    "Crown Castle":"CCI",
    "CSX":"CSX",
    "Cummins":"CMI",
    "CVS Health":"CVS",
    "D.R. Horton":"DHI",
    "Danaher Corporation":"DHR",
    "Darden Restaurants":"DRI",
    "DaVita Inc.":"DVA",
    "John Deere":"DE",
    "Delta Air Lines":"DAL",
    "Dentsply Sirona":"XRAY",
    "Devon Energy":"DVN",
    "Dexcom":"DXCM",
    "Diamondback Energy":"FANG",
    "Digital Realty":"DLR",
    "Discover Financial":"DFS",
    "Dish Network":"DISH",
    "Disney":"DIS",
    "Dollar General":"DG",
    "Dollar Tree":"DLTR",
    "Dominion Energy":"D",
    "Domino's":"DPZ",
    "Dover Corporation":"DOV",
    "Dow Inc.":"DOW",
    "DTE Energy":"DTE",
    "Duke Energy":"DUK",
    "Duke Realty":"DRE",
    "DuPont":"DD",
    "DXC Technology":"DXC",
    "Eastman Chemical Company":"EMN",
    "Eaton Corporation":"ETN",
    "eBay":"EBAY",
    "Ecolab":"ECL",
    "Edison International":"EIX",
    "Edwards Lifesciences":"EW",
    "Electronic Arts":"EA",
    "Eli Lilly and Company":"LLY",
    "Emerson Electric":"EMR",
    "Enphase":"ENPH",
    "Entergy":"ETR",
    "EOG Resources":"EOG",
    "EPAM Systems":"EPAM",
    "Equifax":"EFX",
    "Equinix":"EQIX",
    "Equity Residential":"EQR",
    "Essex Property Trust":"ESS",
    "The Estée Lauder Companies":"EL",
    "Etsy":"ETSY",
    "Everest Re":"RE",
    "Evergy":"EVRG",
    "Eversource":"ES",
    "Exelon":"EXC",
    "Expedia Group":"EXPE",
    "Expeditors International":"EXPD",
    "Extra Space Storage":"EXR",
    "ExxonMobil":"XOM",
    "F5":"FFIV",
    "FactSet":"FDS",
    "Fastenal":"FAST",
    "Federal Realty":"FRT",
    "FedEx":"FDX",
    "Fifth Third Bank":"FITB",
    "First Republic Bank":"FRC",
    "FirstEnergy":"FE",
    "FIS":"FIS",
    "Fiserv":"FISV",
    "Fleetcor":"FLT",
    "FMC Corporation":"FMC",
    "Ford Motor Company":"F",
    "Fortinet":"FTNT",
    "Fortive":"FTV",
    "Fortune Brands Home & Security":"FBHS",
    "Fox Corporation (Class A)":"FOXA",
    "Fox Corporation (Class B)":"FOX",
    "Franklin Templeton":"BEN",
    "Freeport-McMoRan":"FCX",
    "Garmin":"GRMN",
    "Gartner":"IT",
    "Generac":"GNRC",
    "General Dynamics":"GD",
    "General Electric":"GE",
    "General Mills":"GIS",
    "General Motors":"GM",
    "Genuine Parts Company":"GPC",
    "Gilead Sciences":"GILD",
    "Globe Life":"GL",
    "Global Payments":"GPN",
    "Goldman Sachs":"GS",
    "Halliburton":"HAL",
    "Hartford (The)":"HIG",
    "Hasbro":"HAS",
    "HCA Healthcare":"HCA",
    "Healthpeak":"PEAK",
    "Henry Schein":"HSIC",
    "Hershey's":"HSY",
    "Hess Corporation":"HES",
    "Hewlett Packard Enterprise":"HPE",
    "Hilton Worldwide":"HLT",
    "Hologic":"HOLX",
    "The Home Depot":"HD",
    "Honeywell":"HON",
    "Hormel Foods":"HRL",
    "Host Hotels & Resorts":"HST",
    "Howmet Aerospace":"HWM",
    "HP Inc.":"HPQ",
    "Humana":"HUM",
    "Huntington Bancshares":"HBAN",
    "Huntington Ingalls Industries":"HII",
    "IBM":"IBM",
    "IDEX Corporation":"IEX",
    "Idexx Laboratories":"IDXX",
    "Illinois Tool Works":"ITW",
    "Illumina":"ILMN",
    "Incyte":"INCY",
    "Ingersoll Rand":"IR",
    "Intel":"INTC",
    "Intercontinental Exchange":"ICE",
    "International Paper":"IP",
    "The Interpublic Group of Companies":"IPG",
    "International Flavors & Fragrances":"IFF",
    "Intuit":"INTU",
    "Intuitive Surgical":"ISRG",
    "Invesco":"IVZ",
    "IQVIA":"IQV",
    "Iron Mountain":"IRM",
    "J.B. Hunt":"JBHT",
    "Jack Henry & Associates":"JKHY",
    "Jacobs Engineering Group":"J",
    "Johnson & Johnson":"JNJ",
    "Johnson Controls":"JCI",
    "JPMorgan Chase":"JPM",
    "Juniper Networks":"JNPR",
    "Kellogg's":"K",
    "Keurig Dr Pepper":"KDP",
    "KeyCorp":"KEY",
    "Keysight":"KEYS",
    "Kimberly-Clark":"KMB",
    "Kimco Realty":"KIM",
    "Kinder Morgan":"KMI",
    "KLA Corporation":"KLAC",
    "Kraft Heinz":"KHC",
    "Kroger":"KR",
    "L3Harris":"LHX",
    "LabCorp":"LH",
    "Lam Research":"LRCX",
    "Lamb Weston":"LW",
    "Las Vegas Sands":"LVS",
    "Leidos":"LDOS",
    "Lennar":"LEN",
    "Lincoln Financial":"LNC",
    "Linde plc":"LIN",
    "Live Nation Entertainment":"LYV",
    "LKQ Corporation":"LKQ",
    "Lockheed Martin":"LMT",
    "Loews Corporation":"L",
    "Lowe's":"LOW",
    "Lumen Technologies":"LUMN",
    "LyondellBasell":"LYB",
    "M&T Bank":"MTB",
    "Marathon Oil":"MRO",
    "Marathon Petroleum":"MPC",
    "MarketAxess":"MKTX",
    "Marriott International":"MAR",
    "Marsh McLennan":"MMC",
    "Martin Marietta Materials":"MLM",
    "Masco":"MAS",
    "Mastercard":"MA",
    "Match Group":"MTCH",
    "McCormick & Company":"MKC",
    "McDonald's":"MCD",
    "McKesson":"MCK",
    "Medtronic":"MDT",
    "Merck & Co.":"MRK",
    "Meta Platforms":"META",
    "MetLife":"MET",
    "Mettler Toledo":"MTD",
    "MGM Resorts":"MGM",
    "Microchip Technology":"MCHP",
    "Micron Technology":"MU",
    "Microsoft":"MSFT",
    "Mid-America Apartment Communities":"MAA",
    "Moderna":"MRNA",
    "Mohawk Industries":"MHK",
    "Molina Healthcare":"MOH",
    "Molson Coors Beverage Company":"TAP",
    "Mondelez International":"MDLZ",
    "Monolithic Power Systems":"MPWR",
    "Monster Beverage":"MNST",
    "Moody's Corporation":"MCO",
    "Morgan Stanley":"MS",
    "The Mosaic Company":"MOS",
    "Motorola Solutions":"MSI",
    "MSCI":"MSCI",
    "Nasdaq":"NDAQ",
    "NetApp":"NTAP",
    "Netflix":"NFLX",
    "Newell Brands":"NWL",
    "Newmont":"NEM",
    "News Corp (Class A)":"NWSA",
    "News Corp (Class B)":"NWS",
    "NextEra Energy":"NEE",
    "Nielsen Holdings":"NLSN",
    "Nike":"NKE",
    "NiSource":"NI",
    "Nordson Corporation":"NDSN",
    "Norfolk Southern Railway":"NSC",
    "Northern Trust":"NTRS",
    "Northrop Grumman":"NOC",
    "NortonLifeLock":"NLOK",
    "Norwegian Cruise Line Holdings":"NCLH",
    "NRG Energy":"NRG",
    "Nucor":"NUE",
    "Nvidia":"NVDA",
    "NVR":"NVR",
    "NXP Semiconductors":"NXPI",
    "O'Reilly Auto Parts":"ORLY",
    "Occidental Petroleum":"OXY",
    "Old Dominion":"ODFL",
    "Omnicom Group":"OMC",
    "ON Semiconductor":"ON",
    "Oneok":"OKE",
    "Oracle Corporation":"ORCL",
    "Organon & Co.":"OGN",
    "Otis Worldwide":"OTIS",
    "Paccar":"PCAR",
    "Packaging Corporation of America":"PKG",
    "Paramount Global":"PARA",
    "Parker Hannifin":"PH",
    "Paychex":"PAYX",
    "Paycom":"PAYC",
    "PayPal":"PYPL",
    "Penn National Gaming":"PENN",
    "Pentair":"PNR",
    "PepsiCo":"PEP",
    "PerkinElmer":"PKI",
    "Pfizer":"PFE",
    "Philip Morris International":"PM",
    "Phillips 66":"PSX",
    "Pinnacle West":"PNW",
    "Pioneer Natural Resources":"PXD",
    "PNC Financial Services":"PNC",
    "Pool Corporation":"POOL",
    "PPG Industries":"PPG",
    "PPL Corporation":"PPL",
    "Principal Financial Group":"PFG",
    "Procter & Gamble":"PG",
    "Progressive Corporation":"PGR",
    "Prologis":"PLD",
    "Prudential Financial":"PRU",
    "Public Service Enterprise Group":"PEG",
    "PTC":"PTC",
    "Public Storage":"PSA",
    "PulteGroup":"PHM",
    "PVH":"PVH",
    "Qorvo":"QRVO",
    "Quanta Services":"PWR",
    "Qualcomm":"QCOM",
    "Quest Diagnostics":"DGX",
    "Ralph Lauren Corporation":"RL",
    "Raymond James":"RJF",
    "Raytheon Technologies":"RTX",
    "Realty Income":"O",
    "Regency Centers":"REG",
    "Regeneron":"REGN",
    "Regions Financial Corporation":"RF",
    "Republic Services":"RSG",
    "ResMed":"RMD",
    "Robert Half":"RHI",
    "Rockwell Automation":"ROK",
    "Rollins":"ROL",
    "Roper Technologies":"ROP",
    "Ross Stores":"ROST",
    "Royal Caribbean Group":"RCL",
    "S&P Global":"SPGI",
    "Salesforce":"CRM",
    "SBA Communications":"SBAC",
    "Schlumberger":"SLB",
    "Seagate Technology":"STX",
    "Sealed Air":"SEE",
    "Sempra Energy":"SRE",
    "ServiceNow":"NOW",
    "Sherwin-Williams":"SHW",
    "Signature Bank":"SBNY",
    "Simon Property Group":"SPG",
    "Skyworks Solutions":"SWKS",
    "The J.M. Smucker Company":"SJM",
    "Snap-on":"SNA",
    "SolarEdge":"SEDG",
    "Southern Company":"SO",
    "Southwest Airlines":"LUV",
    "Stanley Black & Decker":"SWK",
    "Starbucks":"SBUX",
    "State Street Corporation":"STT",
    "Steris":"STE",
    "Stryker Corporation":"SYK",
    "SVB Financial":"SIVB",
    "Synchrony Financial":"SYF",
    "Synopsys":"SNPS",
    "Sysco":"SYY",
    "T-Mobile US":"TMUS",
    "T. Rowe Price":"TROW",
    "Take-Two Interactive":"TTWO",
    "Tapestry":"TPR",
    "Target Corporation":"TGT",
    "TE Connectivity":"TEL",
    "Teledyne Technologies":"TDY",
    "Teleflex":"TFX",
    "Teradyne":"TER",
    "Tesla":"TSLA",
    "Texas Instruments":"TXN",
    "Textron":"TXT",
    "Thermo Fisher Scientific":"TMO",
    "TJX Companies":"TJX",
    "Tractor Supply":"TSCO",
    "Trane Technologies":"TT",
    "TransDigm Group":"TDG",
    "The Travelers Companies":"TRV",
    "Trimble Inc.":"TRMB",
    "Truist":"TFC",
    "Twitter Inc.":"TWTR",
    "Tyler Technologies":"TYL",
    "Tyson Foods":"TSN",
    "U.S. Bank":"USB",
    "UDR":"UDR",
    "Ulta Beauty":"ULTA",
    "Union Pacific Corporation":"UNP",
    "United Airlines Holdings":"UAL",
    "United Parcel Service":"UPS",
    "United Rentals":"URI",
    "UnitedHealth Group":"UNH",
    "Universal Health Services":"UHS",
    "Valero Energy":"VLO",
    "Ventas":"VTR",
    "Verisign":"VRSN",
    "Verisk":"VRSK",
    "Verizon":"VZ",
    "Vertex Pharmaceuticals":"VRTX",
    "VF Corporation":"VFC",
    "Viatris":"VTRS",
    "Vici Properties":"VICI",
    "Visa Inc.":"V",
    "Vornado Realty Trust":"VNO",
    "Vulcan Materials Company":"VMC",
    "Wabtec":"WAB",
    "Walgreens Boots Alliance":"WBA",
    "Walmart":"WMT",
    "Warner Bros. Discovery":"WBD",
    "Waste Management":"WM",
    "Waters Corporation":"WAT",
    "WEC Energy Group":"WEC",
    "Wells Fargo":"WFC",
    "Welltower":"WELL",
    "West Pharmaceutical Services":"WST",
    "Western Digital":"WDC",
    "WestRock":"WRK",
    "Weyerhaeuser":"WY",
    "Whirlpool Corporation":"WHR",
    "Williams Companies":"WMB",
    "Willis Towers Watson":"WTW",
    "W. W. Grainger":"GWW",
    "Wynn Resorts":"WYNN",
    "Xcel Energy":"XEL",
    "Xylem Inc.":"XYL",
    "Yum! Brands":"YUM",
    "Zebra Technologies":"ZBRA",
    "Zimmer Biomet":"ZBH",
    "Zions Bancorporation":"ZION",
    "Zoetis":"ZTS"
 }